# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: awajsbro <awajsbro@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/26 13:01:54 by awajsbro          #+#    #+#              #
#    Updated: 2018/12/01 16:28:14 by awajsbro         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine

RUN apk update ;\
    apk upgrade ;\
    apk add vim

CMD vim

# docker build -t SKETUVE .
# docker run -it --rm SKETUVE
